# Generated by Django 5.2.5 on 2025-08-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='residents',
            new_name='user',
        ),
    ]
